version: '3'

services:
  db:
    container_name: 'url_shortener_postgres_test'
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=url_shortener_db_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123454321
      - POSTGRES_HOST=localhost
    ports:
      - '5433:5432'
    volumes:
      - ./scripts/structer.sql:/docker-entrypoint-initdb.d/structer.sql
