version: '3'

services:
  db:
    container_name: 'url_shortener_postgres'
    image: postgres
    restart: always
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=url_shortener_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123454321
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./scripts/structer.sql:/docker-entrypoint-initdb.d/structer.sql

  server:
    container_name: 'shortener_url_service'
    image: 'shortener_url_service'
    depends_on:
      - db
    ports:
      - '8082:8082'
      - '8080:8080'
